# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
exclude: ^\.yarn/releases/.*$
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-json
    -   id: check-added-large-files
    -   id: check-merge-conflict
    -   id: check-symlinks
    -   id: check-toml
# JS
-   repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.33.0
    hooks:
    -   id: eslint
        files: \.([jt]sx?|vue)$
        types: [file]
        args: [--fix]
        additional_dependencies:
        -   eslint@8.33.0
        -   eslint-plugin-vue@9.9.0
