name: Mirror to Gitee Repo
on:
  push:
    branches:
      - master
jobs:
  git-mirror:
    uses: deepmodeling/workflows/.github/workflows/mirror_gitee.yml@main
    secrets:
      SYNC_GITEE_PRIVATE_KEY: ${{ secrets.SYNC_GITEE_PRIVATE_KEY }}
