on:
  push:
    branches:
      - master
    tags:
      - v*
  pull_request:
name: Build and deploy on push
jobs:
  build:
    name: yarn build and deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@v2
      with:
        node-version: 14
        cache: 'yarn'
    - run: yarn install
    - run: yarn build
    - run: ln -s index.html dist/404.html
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@releases/v3
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: dist
        BASE_BRANCH: master
        CLEAN: true