on: [push, pull_request]
name: Release to pypi
jobs:
  release-to-pypi:
    name: Release to pypi
    runs-on: ubuntu-latest
    permissions:
        # IMPORTANT: this permission is mandatory for trusted publishing
        id-token: write
    steps:
    - uses: actions/checkout@v4
    - run: pipx run uv tool run --with build[uv] --from build python -m build --installer uv -o python_dist
    - name: Publish a Python distribution to PyPI
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        packages-dir: python_dist/
