on:
  push:
  pull_request:
name: Test
jobs:
  testWithTox:
    name: Test with tox
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - run: pipx run uv pip install --system .
    - run: dpgui -h
